#!/bin/sh

#  Copyright (c) 2023, Advanced Micro Devices, Inc.
#  All rights reserved.
# 
#  Author: Eddie Hung, Advanced Micro Devices, Inc.
# 
#  This file is part of RapidWright.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


# Check that the main jar has been built
# NOTE: Does not check that it is up-to-date
MAIN_JAR=${BASH_SOURCE%/*}/build/libs/main.jar
if [[ ! -f ${MAIN_JAR} ]]; then
    echo "RapidWright not yet compiled. Please run './gradlew compileJava' from '`readlink -f ${BASH_SOURCE%/*}`'"
    exit 1
fi


if [[ $# -eq 0 || "$1" == "--help" || "$1" == "-h" || "$1" == "/?" ]]; then
    echo "./rapidwright com.xilinx.rapidwright.<ClassName> -- to execute main() method of Java class"
    echo "./rapidwright <application>                      -- to execute a specific application"
    echo "./rapidwright --list-apps                        -- to list all available applications"
    echo "./rapidwright jython                             -- to enter interactive Jython shell"
    echo "./rapidwright jython -c \"...\"                  -- to execute specific Jython command"
    exit
fi


# If the first argument is likely to be a class name, then
# execute that Java class' `main()` method
if [[ "$1" == "com.xilinx.rapidwright."* ]]; then
    java -cp ${MAIN_JAR} "$@"
    exit
fi

# If the first argument is "--list" then clear all other
# arguments for the default class that follows
if [[ "$1" == "--list-apps" ]]; then
    shift $#
fi

# Otherwise use the default `MainEntrypoint` class
java -jar ${MAIN_JAR} "$@"
