/*
 * Copyright (c) 2017-2022, Xilinx, Inc.
 * Copyright (c) 2022, Advanced Micro Devices, Inc.
 * All rights reserved.
 *
 * Author: Chris Lavin, Xilinx Research Labs.
 *
 * This file is part of RapidWright.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
/**
 *
 */
package com.xilinx.rapidwright.design;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.stream.Stream;

import com.xilinx.rapidwright.device.BELPin;
import com.xilinx.rapidwright.device.Device;
import com.xilinx.rapidwright.edif.EDIFHierPortInst;
import com.xilinx.rapidwright.util.FileTools;
import org.jspecify.annotations.NonNull;

/**
 * Parses metadata file generated by the Tcl command in rapidwright.tcl/generate_metadata.
 *
 * Created on: May 10, 2016
 */
public class MetadataParser {

    private String line;

    private String nextLine;

    private int lineNumber;

    private String[] tokens;

    private String[] nextTokens;

    private BufferedReader br;

    private String fileName;

    private MDParserState currState = MDParserState.BLOCK_BEGIN;

    private static final String BEGIN = "begin";
    private static final String BLOCK = "block";
    private static final String NAME = "name";
    private static final String CLOCKS = "clocks";
    private static final String PBLOCKS = "pblocks";
    private static final String INPUTS = "inputs";
    private static final String OUTPUTS = "outputs";
    private static final String PBLOCK = "pblock";
    private static final String GRID_RANGES = "grid_ranges";
    private static final String CLOCK = "clock";
    private static final String PERIOD = "period";
    private static final String END = "end";
    private static final String INPUT = "input";
    private static final String OUTPUT = "output";
    private static final String NETNAME = "netname";
    private static final String NUMPRIMS = "numprims";
    private static final String TYPE = "type";
    private static final String MAXDELAY = "maxdelay";
    private static final String MAXNETDELAY = "maxnetdelay";
    private static final String MAXPATH = "maxpath";
    private static final String CONNECTIONS = "connections";
    private static final String PATH = "path";
    private static final String PIN = "pin";
    private static final String PORT = "port";
    private static final String PPLOCS = "pplocs";
    private static final String _ARROW = "-->";

    private enum MDParserState {BLOCK_BEGIN, BLOCK_NAME, BLOCK_PBLOCKS, BLOCK_CLOCKS, BLOCK_INPUTS, BLOCK_OUTPUTS,
                                PBLOCK_BEGIN, PBLOCK_NAME, PBLOCK_GRID_RANGES, PBLOCK_END,
                                CLOCK_BEGIN, CONNECTIONS_EXPLICITNESS, CLOCK_NAME, CLOCK_PERIOD, CLOCK_END,
                                PORT_BEGIN, PORT_NAME, PORT_NET, PORT_NUMPRIMS, PORT_TYPE, PORT_MAXDELAY,
                                PORT_CONNS_BEGIN, PORT_CONNS_PIN, PORT_CONNS_END, PORT_END, PORT_PPLOCS, BLOCK_END};

    private Device dev;

    private Module m;

    public MetadataParser(Device dev, Module m) {
        this.dev = dev;
        this.m = m;
    }

    public String getOriginalInstName(String metadataFileName) {
        File dir = new File(metadataFileName).getParentFile();
        File xciFile = new File(dir.getAbsolutePath() + "/" + dir.getName() + ".xci");
        try {
            BufferedReader br = new BufferedReader(new FileReader(xciFile));
            String line = null;
            while ((line = br.readLine()) != null) {
                if (line.contains("instanceName")) {
                    br.close();
                    return line.substring(line.indexOf('>')+1, line.indexOf("</", 0));
                }
            }
            br.close();
        } catch (FileNotFoundException e) {
            return null;
        } catch (IOException e) {
            return null;
        }
        return null;
    }

    public void parse(String metadataFileName) {
        String originalInstName = getOriginalInstName(metadataFileName);
        this.fileName = metadataFileName;
        int clockCount = -1;
        int pblockCount = -1;
        int inputCount = -1;
        int outputCount = -1;
        int currPrimCount = -1;
        boolean implicitConnections = false;
        Map<Net, List<Port>> netsToPorts = new HashMap<>();
        Port currPort = null;
        String currPBlockName = null;
        String currClockName = null;
        Net currPortNet = null;
        br = FileTools.getProperInputStream(metadataFileName);
        getNextLine();
        getNextLine();
        outer: while (line != null) {
            switch(currState) {
                case BLOCK_BEGIN:{
                    expect(BEGIN, tokens[0]);
                    expect(BLOCK, tokens[1]);
                    currState = MDParserState.BLOCK_NAME;
                    break;
                }
                case BLOCK_NAME:{
                    expect(NAME, tokens[1]);
                    if (originalInstName != null) expect(originalInstName,tokens[2]);
                    if (nextTokens[1].equals(CLOCKS)) {
                        currState = MDParserState.BLOCK_CLOCKS;
                    } else {
                        currState = MDParserState.BLOCK_PBLOCKS;
                    }
                    break;
                }
                case BLOCK_PBLOCKS:{
                    expect(PBLOCKS, tokens[1]);
                    pblockCount = Integer.parseInt(tokens[2]);
                    currState = MDParserState.BLOCK_CLOCKS;
                    break;
                }
                case BLOCK_CLOCKS:{
                    expect(CLOCKS, tokens[1]);
                    clockCount = Integer.parseInt(tokens[2]);
                    currState = MDParserState.BLOCK_INPUTS;
                    break;
                }
                case BLOCK_INPUTS:{
                    expect(INPUTS, tokens[1]);
                    inputCount = Integer.parseInt(tokens[2]);
                    currState = MDParserState.BLOCK_OUTPUTS;
                    break;
                }
                case BLOCK_OUTPUTS:{
                    expect(OUTPUTS, tokens[1]);
                    outputCount = Integer.parseInt(tokens[2]);
                    if (nextTokens[2].equals(PBLOCK)) {
                        currState = MDParserState.PBLOCK_BEGIN;
                    } else if (nextTokens[2].equals(CLOCK)) {
                        currState = MDParserState.CLOCK_BEGIN;
                    } else {
                        currState = MDParserState.CONNECTIONS_EXPLICITNESS;
                    }
                    break;
                }

                case PBLOCK_BEGIN:{
                    expect(BEGIN,tokens[1]);
                    expect(PBLOCK,tokens[2]);
                    currState = MDParserState.PBLOCK_NAME;
                    break;
                }
                case PBLOCK_NAME:{
                    expect(NAME,tokens[1]);
                    currPBlockName = tokens[2];
                    currState = MDParserState.PBLOCK_GRID_RANGES;
                    break;
                }
                case PBLOCK_GRID_RANGES:{
                    expect(GRID_RANGES, tokens[1]);
                    m.setPBlock(line.replace(GRID_RANGES, "").trim());
                    currState = MDParserState.PBLOCK_END;
                    break;
                }
                case PBLOCK_END:{
                    expect(END, tokens[1]);
                    expect(PBLOCK, tokens[2]);
                    pblockCount--;
                    if (pblockCount == 0) {
                        if (clockCount > 0) {
                            currState = MDParserState.CLOCK_BEGIN;
                        } else {
                            currState = MDParserState.CONNECTIONS_EXPLICITNESS;
                        }
                    } else {
                        currState = MDParserState.PBLOCK_BEGIN;
                    }
                    break;
                }

                case CLOCK_BEGIN:{
                    expect(BEGIN,tokens[1]);
                    expect(CLOCK,tokens[2]);
                    currState = MDParserState.CLOCK_NAME;
                    break;
                }
                case CLOCK_NAME:{
                    expect(NAME,tokens[1]);
                    currClockName = tokens[2];
                    currState = MDParserState.CLOCK_PERIOD;
                    break;
                }
                case CLOCK_PERIOD:{
                    expect(PERIOD, tokens[1]);
                    m.addClock(currClockName, Float.parseFloat(tokens[2]));
                    currState = MDParserState.CLOCK_END;
                    break;
                }
                case CLOCK_END:{
                    expect(END, tokens[1]);
                    expect(CLOCK, tokens[2]);
                    clockCount--;
                    if (clockCount == 0) {
                        currState = MDParserState.CONNECTIONS_EXPLICITNESS;
                    } else {
                        currState = MDParserState.CLOCK_BEGIN;
                    }
                    break;
                }
                case CONNECTIONS_EXPLICITNESS: {
                    if (tokens[1].equals(CONNECTIONS)) {
                        implicitConnections = tokens[2].equals("implicit");
                        if (!implicitConnections && !tokens[2].equals("explicit")) {
                            expect("<explicit|implicit>", tokens[2]);
                        }
                        currState = MDParserState.PORT_BEGIN;
                        break;
                    }
                    //fallthrough
                }
                case PORT_BEGIN:{
                    expect(BEGIN,tokens[1]);
                    currPort = new Port();
                    if (inputCount > 0) {
                        expect(INPUT, tokens[2]);
                        inputCount--;
                        currPort.setOutputPort(false);
                    } else if (outputCount > 0) {
                        expect(OUTPUT, tokens[2]);
                        currPort.setOutputPort(true);
                        outputCount--;
                    } else {
                        throw new RuntimeException("More ports than expected");
                    }
                    currState = MDParserState.PORT_NAME;
                    break;
                }
                case PORT_NAME:{
                    expect(NAME,tokens[1]);
                    currPort.setName(tokens[2]);
                    if (nextTokens[1].equals(TYPE)) {
                        currState = MDParserState.PORT_TYPE;
                    } else if (nextTokens[1].equals(PPLOCS)) {
                        currState = MDParserState.PORT_PPLOCS;
                    } else {
                        currState = MDParserState.PORT_NET;
                    }
                    break;
                }
                case PORT_PPLOCS:{
                    expect(PPLOCS, tokens[1]);
                    currPort.setPartitionPinLoc(dev.getTile(tokens[2]));
                    if (nextTokens[1].equals(TYPE)) {
                        currState = MDParserState.PORT_TYPE;
                    } else {
                        currState = MDParserState.PORT_NET;
                    }
                    break;
                }
                case PORT_NET:{
                    expect(NETNAME, tokens[1]);
                    currPortNet = m.getNet(tokens[2]);
                    if (currPortNet==null) {
                        String parentNetName = m.getNetlist().getParentNetName(tokens[2]);
                        currPortNet = m.getNet(parentNetName);
                        if (currPortNet==null) {
                            currPortNet = new Net(parentNetName);
                            m.addNet(currPortNet);
                        }
                    }
                    currState = MDParserState.PORT_NUMPRIMS;
                    break;
                }
                case PORT_NUMPRIMS:{
                    expect(NUMPRIMS, tokens[1]);
                    currPrimCount = Integer.parseInt(tokens[2]);
                    currState = MDParserState.PORT_TYPE;
                    break;
                }
                case PORT_TYPE:{
                    expect(TYPE, tokens[1]);
                    expect(currPort.isOutPort() ? OUTPUT : INPUT,tokens[2]);
                    String type = tokens[3];
                    if (type.equals(CLOCK)) {
                        if (tokens[4].equals("local")) currPort.setType(PortType.LOCAL_CLOCK);
                        else if (tokens[4].equals("global")) currPort.setType(PortType.GLOBAL_CLOCK);
                        else if (tokens[4].equals("regional")) currPort.setType(PortType.REGIONAL_CLOCK);
                        else expect("<local|global|regional>", tokens[4]);
                    }
                    else if (type.equals("signal")) currPort.setType(PortType.SIGNAL);
                    else if (type.equals("ground")) currPort.setType(PortType.GROUND);
                    else if (type.equals("power")) currPort.setType(PortType.POWER);
                    else if (type.equals("unconnected")) currPort.setType(PortType.UNCONNECTED);
                    else if (type.equals("dontcare")) currPort.setType(PortType.DONT_CARE);
                    else if (type.equals("unknown")) currPort.setType(PortType.UNKNOWN);
                    else expect("<signal|ground|power|dontcare|unknown>",tokens[3]);
                    currState = MDParserState.PORT_MAXDELAY;
                    break;
                }
                case PORT_MAXDELAY:{
                    expect(MAXDELAY,tokens[1]);
                    currPort.setWorstCasePortDelay(Float.parseFloat(tokens[2]));
                    if (nextTokens[1].equals(END)) {
                        currState = MDParserState.PORT_END;
                        if (implicitConnections) {
                            if (currPort.getType()!=PortType.UNCONNECTED) {
                                netsToPorts.computeIfAbsent(currPortNet, x -> new ArrayList<>()).add(currPort);
                            }
                        }
                    } else {
                        currState = MDParserState.PORT_CONNS_BEGIN;
                    }
                    break;
                }
                case PORT_CONNS_BEGIN:{
                    expect(BEGIN,tokens[1]);
                    expect(CONNECTIONS, tokens[2]);
                    if (nextTokens[1].equals(END)) {
                        currPort.setType(PortType.UNCONNECTED);
                        currState = MDParserState.PORT_CONNS_END;
                    }
                    else currState = MDParserState.PORT_CONNS_PIN;
                    break;
                }
                case PORT_CONNS_PIN:{
                    if (tokens[1].equals(PIN)) {
                        String logPinName = tokens[2];
                        if (tokens.length > 4) {
                            String siteName = tokens.length > 3 ? tokens[3] : null;
                            String sitePinName = tokens.length > 4 ? tokens[4] : null;
                            String pinName = sitePinName.substring(sitePinName.indexOf('/')+1);
                            if (tokens.length > 5 && currPort.isOutPort()) {
                                SiteInst i = m.getSiteInstAtSite(dev.getSite(siteName));
                                if (i.getSitePinInst(pinName) == null) {
                                    sitePinName = tokens.length > 5 ? tokens[5] : sitePinName;
                                    pinName = sitePinName.substring(sitePinName.indexOf('/')+1);
                                }
                            }
                            SiteInst si = m.getSiteInstAtSite(dev.getSite(siteName));

                            if (si==null) {
                                throw new RuntimeException("did not find site inst at "+siteName+" in device "+dev);
                            }

                            SitePinInst p = si.getSitePinInst(pinName);
                            if (p == null) {
                                Net n = si.getNetFromSiteWire(pinName);
                                if (n == null) {
                                    // Check if alternate site type
                                    if (si.getSiteTypeEnum() != si.getSite().getSiteTypeEnum()) {
                                        String altPinName = si.getAlternateSitePinName(pinName);
                                        n = si.getNetFromSiteWire(altPinName);
                                    }
                                    if (n == null)
                                        throw new RuntimeException("ERROR: Don't know net of " + sitePinName);
                                }
                                p = new SitePinInst(si.getSite().isOutputPin(pinName), pinName, si);
                                n.addPin(p);
                            }
                            //Skip inputs on an output port. Happens if the output signal is used internally
                            if (p.isOutPin() == currPort.isOutPort()) {
                                currPort.addSitePinInst(p);
                            } else {
                                if (!currPort.isOutPort()) {
                                    throw new RuntimeException("Output pin on input port "+currPort.getName()+": "+p);
                                }
                            }
                        }
                    } else if (tokens[1].equals(PORT)) {
                        currPort.addPassThruPortName(tokens[2]);
                    } else {
                        expect("<pin|port>",tokens[1]);
                    }
                    if (nextTokens[1].equals(END)) {
                        currState = MDParserState.PORT_CONNS_END;
                    }
                    break;
                }
                case PORT_CONNS_END:{
                    expect(END, tokens[1]);
                    expect(CONNECTIONS, tokens[2]);
                    currState = MDParserState.PORT_END;
                    break;
                }
                case PORT_END:{
                    expect(END,tokens[1]);
                    expect(currPort.isOutPort() ? OUTPUT : INPUT, tokens[2]);
                    m.addPort(currPort);
                    currPort = null;
                    if (nextTokens[1].equals(BEGIN)) {
                        currState = MDParserState.PORT_BEGIN;
                    }
                    else if (nextTokens[0].equals(END)) {
                        currState = MDParserState.BLOCK_END;
                    }
                    break;
                }
                case BLOCK_END:{
                    expect(END,tokens[0]);
                    expect(BLOCK,tokens[1]);
                    break outer;
                }
                default:{
                    break;
                }
            }
            getNextLine();
        }
        try {
            br.close();
        } catch (IOException e) {
            throw new RuntimeException("ERROR: IOException encountered on closing file " + fileName + "\nStack Trace:");
        }

        if (implicitConnections) {
            addPassThruNames(netsToPorts);
            netsToPorts.forEach((net, ports) -> {
                for (Port port : ports) {
                    createImplicitConnections(net, port);
                }
            });

        } else {
            for (Port port : m.getPorts()) {
                checkForOutputPortSource(port);
            }
        }
    }

    /**
     * For ports on the same net, check if we ran into a Vivado issue where it does not route
     * an output BEL to an SPI
     * @param port the port to check
     */
    private void checkForOutputPortSource(Port port) {
        if (!port.isOutPort()) {
            return;
        }
        if (!port.getSitePinInsts().isEmpty() || port.getType() == PortType.GROUND || port.getType() == PortType.POWER) {
            return;
        }
        //Any input among passthru ports?
        if (port.getPassThruPortNames().stream().map(name->m.getPort(name)).anyMatch(p->!p.isOutPort())) {
            return;
        }
        throw new NoSuchElementException("in module "+m+" we have output port "+port+" which neither passes through an input nor has any assigned SPIs");
    }

    private void addPassThruNames(Map<Net, List<Port>> netsToPorts) {
        for (List<Port> passedThru : netsToPorts.values()) {
            for (Port from : passedThru) {
                for (Port to : passedThru) {
                    if (from==to) {
                        continue;
                    }
                    from.addPassThruPortName(to.getName());
                }
            }
        }
    }

    private void createImplicitConnections(Net currPortNet, Port currPort) {
        if (currPort.getType().equals(PortType.POWER) || currPort.getType().equals(PortType.GROUND) || currPort.getType().equals(PortType.UNCONNECTED)) {
            return;
        }
        if (currPortNet==null) {
            throw new RuntimeException("no net for port "+currPort);
        }
        List<EDIFHierPortInst> physicalPins = m.getNetlist().getPhysicalPins(currPortNet);

        if (physicalPins==null || physicalPins.isEmpty()) {
            //Need to figure out if this is allowed
            if (!currPort.isOutPort()) {
                //Port is actually unused
                return;
            }
            if (currPort.getPassThruPortNames().stream().map(p->m.getPort(p)).anyMatch(p->!p.isOutPort())) {
                //Passthru for an input
                return;
            }
            throw new RuntimeException("no prims are driving output port "+currPort.getName());
        }

        physicalPins.stream()
                .flatMap(pin -> getSitePinsFromEdifPort(currPortNet, currPort, pin))
                .distinct()
                .forEach(sitePinInst -> {
                    currPort.addSitePinInst(sitePinInst);
                    if (sitePinInst.getNet() != currPortNet) {
                        currPortNet.addPin(sitePinInst);
                    }
                });

        if (currPort.getSitePinInsts().isEmpty() && currPort.isOutPort() && currPort.getPassThruPortNames().isEmpty()) {
            throw new RuntimeException("in creating implicit module connections, no pin for "+currPort+" is routed to Site Pin");
        }
    }

    private @NonNull Stream<SitePinInst> getSitePinsFromEdifPort(Net currPortNet, Port currPort, EDIFHierPortInst pin) {
        //Is this an internal use of an output port?
        if (pin.isOutput() != currPort.isOutPort()) {
            return Stream.empty();
        }

        Cell cell = pin.getPhysicalCell(m);
        if (cell == null) {
            throw new RuntimeException("did not find physical cell for " + pin + " in " + m + ". Are macro unisims expanded?");
        }

        SiteInst siteInst = cell.getSiteInst();
        return cell.getPinMappingsL2P()
                .get(pin.getPortInst().getName())
                .stream()
                .flatMap(physical -> getSitePinNamesFromBelPin(currPortNet, pin, physical, cell))
                .map(p -> getSitePinsInstFromName(currPort, p, siteInst));
    }

    private static @NonNull SitePinInst getSitePinsInstFromName(Port currPort, String sitePinName, SiteInst siteInst) {
        String realSitePinName = sitePinName;
        if (siteInst.getSiteTypeEnum() != siteInst.getSite().getSiteTypeEnum()) {
            realSitePinName = siteInst.getPrimarySitePinName(sitePinName);
        }

        SitePinInst spi = siteInst.getSitePinInst(realSitePinName);
        if (spi == null) {
            spi = new SitePinInst(currPort.isOutPort(), realSitePinName, siteInst);
        }
        return spi;
    }

    private @NonNull Stream<String> getSitePinNamesFromBelPin(Net currPortNet, EDIFHierPortInst pin, String physical, Cell cell) {
        List<String> spis = DesignTools.getAllRoutedSitePinsFromPhysicalPin(cell, currPortNet, physical);
        if (spis.isEmpty()) {
            String newSitePin = bringOutputToSitePin(cell, currPortNet, pin.getPortInst().getName(), physical);
            return Stream.of(newSitePin);
        }
        return spis.stream();
    }

    /**
     * Handle the rare case where Vivado does not route an output to a Site Pin. We have to choose a Site Pin ourselves.
     */
    private String bringOutputToSitePin(Cell cell, Net net, String logicalPin, String pin) {
        BELPin cellPin = Objects.requireNonNull(cell.getBEL().getPin(pin));
        String sitePinName = cellPin.getConnectedSitePinName();
        if (sitePinName==null) {
            sitePinName = cell.getCorrespondingSitePinName(logicalPin, pin, null);
        }
        if (sitePinName==null) {
            throw new RuntimeException("did not find Site Pin for "+logicalPin+" physical pin "+pin+" on "+cell.getSite()+"."+cell.getBEL() +" "+cell.getType());
        }
        SitePinInst existing = cell.getSiteInst().getSitePinInst(sitePinName);
        if (existing != null) {
            throw new RuntimeException("cannot bring cell pin "+cell+"."+pin+" with net "+net+" out to site pin "+sitePinName+" as it is used by "+existing.getNet());
        }
        SitePinInst newPin = new SitePinInst(cellPin.isOutput(), sitePinName, cell.getSiteInst());
        if (!cell.getSiteInst().routeIntraSiteNet(net, cellPin, newPin.getBELPin())) {
            throw new RuntimeException("while bringing cellpin "+cell+"."+pin+" out to site pin "+sitePinName+", failed to route site net");
        }
        return sitePinName;
    }

    private boolean expect(String expected, String found) {
        if (!expected.equals(found)) {
            throw new RuntimeException("\nERROR: While parsing "+fileName+":\n   '" +
                line + "' (line number " + lineNumber + ")\n" + "   Expected: '" +
                    expected + "'\n      Found: '" + found + "'\nStack Trace:");
        }
        return true;
    }

    private void getNextLine() {
        try {
            tokens = nextTokens;
            line = nextLine;
            nextLine = br.readLine();
            lineNumber++;
            while (nextLine != null && (nextLine.trim().isEmpty() || nextLine.startsWith("#"))) {
                nextLine = br.readLine();
                lineNumber++;
            }
            if (nextLine != null) {
                nextLine = nextLine.replace("\\\\", "\\");
                nextTokens = nextLine.split("\\s+");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        // Test parser
        if (args.length != 2) {
            System.out.println("USAGE: <module.dcp> <metadata.txt>");
            return;
        }
        Design d = Design.readCheckpoint(args[0]);
        Module m = new Module(d,args[1]);
    }
}
