/* 
 * Copyright (c) 2022 Xilinx, Inc. 
 * All rights reserved.
 *
 * Author: Chris Lavin, Xilinx Research Labs.
 *  
 * This file is part of RapidWright. 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 */
 
// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: References.capnp

package com.xilinx.rapidwright.interchange;

public final class References {
  public enum ReferenceType {
    ROOT,
    ROOT_VALUE,
    PARENT,
    _NOT_IN_SCHEMA,
  }

  public enum ImplementationType {
    ENUMERATOR,
    _NOT_IN_SCHEMA,
  }


public static final class Schemas {
public static final org.capnproto.SegmentReader b_900a370ddc2fbe15 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0015\u00be\u002f\u00dc\r\u0037\n\u0090" +
   "\u0011\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0086\u006a\u0079\u0093\u0068\u002c\u0008\u00a0" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u004f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0066\u0065\u0072\u0065\u006e\u0063" +
   "\u0065\u0073\u002e\u0063\u0061\u0070\u006e\u0070" +
   "\u003a\u0052\u0065\u0066\u0065\u0072\u0065\u006e" +
   "\u0063\u0065\u0054\u0079\u0070\u0065\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0011\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0072\u006f\u006f\u0074\u0000\u0000\u0000\u0000" +
   "\u0072\u006f\u006f\u0074\u0056\u0061\u006c\u0075" +
   "\u0065\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0061\u0072\u0065\u006e\u0074\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_9285cac596a6bd07 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0007\u00bd\u00a6\u0096\u00c5\u00ca\u0085\u0092" +
   "\u0011\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0086\u006a\u0079\u0093\u0068\u002c\u0008\u00a0" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\"\u0001\u0000\u0000" +
   "\u0025\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u001f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0066\u0065\u0072\u0065\u006e\u0063" +
   "\u0065\u0073\u002e\u0063\u0061\u0070\u006e\u0070" +
   "\u003a\u0049\u006d\u0070\u006c\u0065\u006d\u0065" +
   "\u006e\u0074\u0061\u0074\u0069\u006f\u006e\u0054" +
   "\u0079\u0070\u0065\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u005a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u006e\u0075\u006d\u0065\u0072\u0061\u0074" +
   "\u006f\u0072\u0000\u0000\u0000\u0000\u0000\u0000" + "");
}
}

