/*
 * Copyright (c) 2026, Advanced Micro Devices, Inc.
 * All rights reserved.
 *
 * This file is part of RapidWright.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.xilinx.rapidwright.edif;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;

/**
 * A fixed set of ASCII Strings, any of which can be found from a sequence of bytes (e.g. a token in a buffer)
 * without creating a String, using a perfect hash generated by GNU gperf.
 *
 * The hash of a sequence is the same as that of the C function gperf generates: its length plus the "associated
 * value" of the byte at each of two positions (fixed, or {@link #LAST} for the last byte), i.e.
 * {@code length + value[b1] + value[b2]}. gperf chooses the positions and values so that every String has a
 * different hash, and the hash of every String is small (less than 256), so that the hash is the String's slot in
 * small tables: of lengths, and of characters (each String's bytes in a block of {@link #maxLength} bytes). Finding
 * a sequence reads its two hashed bytes and their values, then the length in its slot, then compares its bytes with
 * that slot's characters. A sequence whose length is outside that of the Strings, or that has a byte with no value
 * of its own (which gets the default value, greater than the hash of any String), is rejected before reading a slot.
 * {@link #find(byte[], int, int)} returns the slot, so callers keep anything to do with a String (e.g. the String
 * itself) in an array indexed by slot (see {@link #slotOf(int)}).
 *
 * To (re)generate the positions and values for a list of Strings (e.g. when the list changes): put one String per
 * line in a file (with no other content) and run {@code gperf -m 1000 file} (GNU gperf 3.1; -m 1000 searches longer
 * for a smaller table). In the C it writes, the hash() function returns {@code len + asso_values[(unsigned
 * char)str[p1]] + asso_values[(unsigned char)str[p2]]}, giving the two positions ({@code str[len - 1]} is
 * {@link #LAST}); and asso_values[] has the value of each byte: the default value is the most frequent one
 * (MAX_HASH_VALUE + 1), and every other entry is given as a (character, value) pair. The constructor checks that
 * every String has a different hash, so that a list that no longer matches its values fails when it is built.
 */
final class PerfectStringTable {
    /** Position of the last byte of a sequence */
    static final int LAST = -1;

    private final int minLength;
    private final int maxLength;
    private final int position1;
    private final int position2;
    /** The value of each byte, from 0 to 255 */
    private final byte[] values;
    /** For each slot (hash), the length of the String in it, or 0 if there is none */
    private final byte[] lengths;
    /** For each slot, the bytes of the String in it, from slot * maxLength */
    private final byte[] chars;
    /** For each slot, the String in it, or null */
    private final String[] strings;
    /** The slot of each String, in the order given to the constructor */
    private final int[] slotsOfStrings;

    /**
     * @param description What the Strings are, for exception messages.
     * @param strings The Strings: each of 1 to 255 ASCII characters.
     * @param position1 The position of the first byte that is hashed (from 0), or {@link #LAST}.
     * @param position2 The position of the second byte that is hashed, or {@link #LAST}.
     * @param defaultValue The value of every byte that has no other value.
     * @param charValues The value of every other byte, as (character, value) pairs. Values range from 0 to 255.
     */
    PerfectStringTable(String description, String[] strings, int position1, int position2, int defaultValue,
                       int... charValues) {
        final int n = strings.length;
        this.position1 = position1;
        this.position2 = position2;
        values = new byte[256];
        Arrays.fill(values, checkedByte(description, defaultValue));
        for (int i = 0; i + 1 < charValues.length; i += 2) {
            values[charValues[i] & 0xff] = checkedByte(description, charValues[i + 1]);
        }
        final byte[][] bytes = new byte[n][];
        int minLength = Integer.MAX_VALUE;
        int maxLength = 0;
        for (int i = 0; i < n; i++) {
            final String s = strings[i];
            for (int j = 0; j < s.length(); j++) {
                if (s.charAt(j) >= 0x80) {
                    throw new IllegalArgumentException(description + ": " + s + " is not ASCII");
                }
            }
            if (s.isEmpty() || s.length() > 255) {
                throw new IllegalArgumentException(description + ": " + s + " is not 1 to 255 characters long");
            }
            bytes[i] = s.getBytes(StandardCharsets.US_ASCII);
            minLength = Math.min(minLength, s.length());
            maxLength = Math.max(maxLength, s.length());
        }
        this.minLength = minLength;
        this.maxLength = maxLength;
        if (Math.max(position1, position2) >= minLength) {
            throw new IllegalArgumentException(description + ": a hashed position is beyond the shortest String");
        }
        // Every String must have a different hash, smaller than that of any sequence with a byte of default value
        slotsOfStrings = new int[n];
        int maxHash = 0;
        for (int i = 0; i < n; i++) {
            final int hash = hash(bytes[i], 0, bytes[i].length);
            if (hash > (defaultValue & 0xff)) {
                throw new IllegalArgumentException(description + ": the hash of " + strings[i] + " is not smaller "
                        + "than that of a sequence with a byte of default value; regenerate the values with gperf");
            }
            for (int j = 0; j < i; j++) {
                if (slotsOfStrings[j] == hash) {
                    throw new IllegalArgumentException(description + ": " + strings[j] + " and " + strings[i]
                            + " have the same hash; regenerate the values with gperf");
                }
            }
            slotsOfStrings[i] = hash;
            maxHash = Math.max(maxHash, hash);
        }
        lengths = new byte[maxHash + 1];
        chars = new byte[(maxHash + 1) * maxLength];
        this.strings = new String[maxHash + 1];
        for (int i = 0; i < n; i++) {
            final int slot = slotsOfStrings[i];
            lengths[slot] = (byte) bytes[i].length;
            System.arraycopy(bytes[i], 0, chars, slot * maxLength, bytes[i].length);
            this.strings[slot] = strings[i];
        }
    }

    private static byte checkedByte(String description, int value) {
        if (value < 0 || value > 255) {
            throw new IllegalArgumentException(description + ": value " + value + " is not from 0 to 255");
        }
        return (byte) value;
    }

    /** The hash of a sequence whose length is from minLength to maxLength */
    private int hash(byte[] buffer, int start, int length) {
        final int b1 = buffer[start + (position1 == LAST ? length - 1 : position1)];
        final int b2 = buffer[start + (position2 == LAST ? length - 1 : position2)];
        return length + (values[b1 & 0xff] & 0xff) + (values[b2 & 0xff] & 0xff);
    }

    /**
     * Find the String whose bytes are exactly the given ones.
     * @param buffer The buffer holding the bytes.
     * @param start The offset of the first byte in the buffer.
     * @param length The number of bytes.
     * @return The slot of the String, or -1 if none matches.
     */
    int find(byte[] buffer, int start, int length) {
        // Also rejects an empty sequence, which has no byte to hash
        if (length < minLength || length > maxLength) {
            return -1;
        }
        final int slot = hash(buffer, start, length);
        // An empty slot has length 0, which no sequence here has
        if (slot >= lengths.length || (lengths[slot] & 0xff) != length) {
            return -1;
        }
        final int base = slot * maxLength;
        for (int j = 0; j < length; j++) {
            if (buffer[start + j] != chars[base + j]) {
                return -1;
            }
        }
        return slot;
    }

    /** @return The number of slots (the largest hash of a String + 1) */
    int slotCount() {
        return lengths.length;
    }

    /** @return The slot of the String at an index of the array given to the constructor */
    int slotOf(int index) {
        return slotsOfStrings[index];
    }

    /** @return The String in a slot, or null if there is none */
    String get(int slot) {
        return strings[slot];
    }

    /** @return A new array of the String in each slot (or null) */
    String[] stringsBySlot() {
        return strings.clone();
    }
}
