name: Submodule refs on origin

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: |
          git submodule foreach --recursive git fetch --unshallow

      - run: |
          git submodule foreach --recursive git merge-base --is-ancestor HEAD origin/master

