name: Check For Tab Characters

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
              fetch-depth: "0"
      - run: |
          make check_tabs

